#!/bin/bash -e
# The assemble script builds the application artifacts from a source and 
# places them into appropriate directories inside the image.

echo "Custom assemble script invoked"

# Execute the default S2I script
/usr/local/s2i/assemble

# You can write S2I scripts in any programming language, as long as the 
# scripts are executable inside the builder image.


chmod 0777 /home/jboss
